{
 "title": "Microservices",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Compute", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"social-network\", container!=\"jaeger-agent\", container!=\"\"}[1m])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{namespace=\"social-network\", container!=\"jaeger-agent\", container!=\"\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"social-network\"}[1m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sent Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"social-network\"}[1m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Write IOPS",
   "type": "graph",
   "description": "Write IOPS",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "increase(openebs_writes{}[1m])/60",
     "legendFormat": "{{openebs_pvc}}"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "graph",
   "description": "Ready IOPS",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "increase(openebs_reads{}[1m])/60",
     "legendFormat": "{{openebs_pvc}}"
    }
   ]
  },
  {
   "title": "Write Throughput",
   "type": "graph",
   "description": "Write Throughput",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "increase(openebs_write_block_count{}[1m])*4096/60",
     "legendFormat": "{{openebs_pvc}}"
    }
   ]
  },
  {
   "title": "Read Throughput",
   "type": "graph",
   "description": "Read Throughput",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "increase(openebs_read_block_count{}[1m])*4096/60",
     "legendFormat": "{{openebs_pvc}}"
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "graph",
   "description": "Disk Space",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    { "expr": "openebs_actual_used{}", "legendFormat": "{{openebs_pvc}}" }
   ]
  },
  { "title": "Jaeger Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Total Number of Dropped Spans",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "jaeger_collector_spans_dropped_total",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 40 },
   "targets": [
    { "expr": "jaeger_collector_queue_length", "legendFormat": "{{host}}" }
   ]
  }
 ]
}