apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations: {}
  labels:
    name: devicelocalpv
  name: devicelocalpv
  namespace: monitoring
spec:
  endpoints:
  - path: /metrics
    port: metrics
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      name: openebs-device-node
